# .travis.yml for HSTR

language: c

os:
  - linux
  - osx
  
addons:
  apt:
    packages:
      - autotools-dev
      - libreadline-dev
      - libncursesw5-dev

compiler:
  - gcc
  - clang

matrix:
  include:
    - if: branch = master
      compiler: gcc
      os: osx
      script: brew install --HEAD jq && brew test jq
    - if: branch = master
      compiler: clang
      os: osx
      script: brew install --HEAD jq && brew test jq

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - aclocal
  - automake --force-missing --add-missing
  - autoconf
